# Site settings
title:       Tony Gaeta
email:       tony.gaeta@gmail.com
author:      Tony Gaeta
description: "Husband • Father • Coder • Runner • St. Pete, FL"
baseurl:     ""
url:         "http://tonygaeta.com"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: tgaeta
bitbucket_username:
stackoverflow_id: tgaeta
twitter_username: tgaeta
google_plus_id:
linkedin_username: tgaeta
angellist_username:
medium_id: tgaeta
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /blog/:year/:month/:day/:title/
paginate:     4
sass:
  compressed: true

# Gems
gems: [jekyll-paginate]
